### PR TITLE
docs: update readme

### PR DESCRIPTION
**Pull request by lindsaymoralesb**

### CODE REVIEW

**Comment by lindsaymoralesb** [comment]
@all-contributors please add @lindsaymoralesb for code

**Comment by lindsaymoralesb** [comment]
https://github.com/all-contributors please add @ChrisFernandezVivas for code

**Comment by lindsaymoralesb** [comment]
@allcontributors please add @ChrisFernandezVivas for code

**Comment by lindsaymoralesb** [comment]
@allcontributors please add @jsanchez556 for code

**Comment by lindsaymoralesb** [comment]
@allcontributors please add @aguzmant103 for projectManagement

**Review by aguzmant103 — APPROVED** [review]

**Pull request merged**
